spring.application.name=soporte-tecnico-api

# Puerto del servidor
server.port=8080

# Configuracion de Swagger 
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Formato de fecha legible en las respuestas JSON
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.time-zone=America/Lima
spring.output.ansi.enabled=ALWAYS
